Workiva/r_tree

README.md

Add Travis-CI Badge to readme

---

pubspec.yaml

Update pubspec for Pub

---

lib/src/r_tree/r_tree.dart
test/r_tree/r_tree_test.dart

@jeffhilleman-wf @kyleshattuck-wf

Clone search result if querying a leaf node directly.

---

lib/src/r_tree/node.dart

@travissanderson-wf @kyleshattuck-wf @johnbland-wf

Add Covariant to Node's addChild and removeChild

---

benchmark/benchmarks.dart
lib/src/r_tree/leaf_node.dart
lib/src/r_tree/node.dart
lib/src/r_tree/non_leaf_node.dart
lib/src/r_tree/r_tree.dart

@travissanderson-wf @kyleshattuck-wf

Make analyzer Strong mode compliant

---

pubspec.yaml

Pulls Included in Release:
* [Update README.md](https://github.com/Workiva/r_tree/pull/8)
* [Add Covariant to Node's addChild and removeChild](https://github.com/Workiva/r_tree/pull/9)
* [Make analyzer Strong mode compliant](https://github.com/Workiva/r_tree/pull/10)
* [Get with the times! Add smithy, codecov, dart_dev, etc](https://github.com/Workiva/r_tree/pull/11)
* [Clone search result if querying a leaf node directly.](https://github.com/Workiva/r_tree/pull/7)
Requested by: @tayloranderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.0.1...Workiva:release_r_tree_1_0_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.0.1...1.0.2
The logs for the request that created this PR can be found …

RM-12194 Release r_tree 1.0.2

---

pubspec.yaml

Pulls Included in Release:
* [Reduce the garbage collection overhead of repeated calls to overlaps](https://github.com/Workiva/r_tree/pull/13)
Requested by: @kyleshattuck-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.0.2...Workiva:release_r_tree_1_0_3
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.0.2...1.0.3

RM-22713 Release r_tree 1.0.3

---

.travis.yml
Dockerfile
benchmark/index.html
lib/r_tree.dart
lib/src/r_tree/non_leaf_node.dart
pubspec.yaml
test/r_tree/r_tree_test.dart

r_tree is not usable in Dart 2.
- Adjust dependencies for dart 2
- Adjust CI
- Use constants that work under Dart 1 & 2

Dart 2 fixes for r_tree

---

pubspec.yaml

* [Dart 2 fixes for r_tree](https://github.com/Workiva/r_tree/pull/21)
Requested by: @travissanderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.0.4...Workiva:release_r_tree_1.0.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.0.4...1.0.5

RM-40780 Release r_tree 1.0.5

---

CHANGELOG.md
README.md
benchmark/benchmarks.dart
example/index.html
example/main.dart
lib/r_tree.dart
lib/src/r_tree/leaf_node.dart
lib/src/r_tree/node.dart
lib/src/r_tree/non_leaf_node.dart
lib/src/r_tree/r_tree.dart
lib/src/r_tree/r_tree_contributor.dart
lib/src/r_tree/r_tree_datum.dart
pubspec.yaml
test/r_tree/leaf_node_test.dart
test/r_tree/node_test.dart
test/r_tree/r_tree_test.dart
tool/dev.dart

Added some fancy fluff to improve our score on https://pub.dartlang.org/packages/r_tree#-analysis-tab-.
@tayloranderson-wf @robbecker-wf

Pub page improvements

---

CHANGELOG.md
pubspec.yaml

* [Pub page improvements](https://github.com/Workiva/r_tree/pull/23)
Requested by: @tayloranderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.0.5...Workiva:release_r_tree_1.0.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.0.5...1.0.6

RM-40947 Release r_tree 1.0.6

---

.travis.yml
lib/src/r_tree/leaf_node.dart
lib/src/r_tree/node.dart
lib/src/r_tree/non_leaf_node.dart
lib/src/r_tree/r_tree.dart
test/r_tree/leaf_node_test.dart
test/r_tree/node_test.dart
test/r_tree/non_leaf_node_test.dart
test/r_tree/r_tree_test.dart

Allow more granular filtering than simply a container rectangle

DT-19419 Add filter for search method

---

pubspec.yaml

* [CPLAT-7476: Run tests with dart2js](https://github.com/Workiva/r_tree/pull/25)
* [DT-19419 Add filter for search method](https://github.com/Workiva/r_tree/pull/27)
Requested by: @tayloranderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.0.6...Workiva:release_r_tree_1.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.0.6...1.1.0

RM-41801 Release r_tree 1.1.0

---

pubspec.yaml

* [Update change log](https://github.com/Workiva/r_tree/pull/29)
* [Vanilla Dart images Need Updating](https://github.com/Workiva/r_tree/pull/34)
* [Raise Max Versions](https://github.com/Workiva/r_tree/pull/37)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/1.1.0...Workiva:release_r_tree_1.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/1.1.0...1.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5495726291288064/?pull_numbe …

RM-86320 Release r_tree 1.1.1

---

skynet.yaml

This adds a skynet config that verifies that the github workflow passes so that the RM pipeline doesn't fail and no manual intervention is required.

FW-142 Add skynet config that verifies that github actions passes

---

skynet.yaml

Update to latest version of the github ci verifier image that fixes the rate limit issue.
Update to latest image of the github ci verifier.
Update to latest image of the github ci verifier.

FW-173 Update github ci image

---

CHANGELOG.md

Update changelog for v2

---

pubspec.yaml

* [Variety of performance improvements](https://github.com/Workiva/r_tree/pull/58)
* [Change updateBoundingRect to be non-breaking](https://github.com/Workiva/r_tree/pull/66)
* [DT-23494 DT-23495 Strengthen test assertions and correct internal tree node state](https://github.com/Workiva/r_tree/pull/67)
* [Update ci badge](https://github.com/Workiva/r_tree/pull/68)
Requested by: @travissanderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/2.1.4...Workiva:release_r_tree_2.1.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/2.1.4...2.1.5
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6122762573840 …

RM-221630 Release r_tree 2.1.5

---

CHANGELOG.md

Updates the changelog so we can tag 2.1.6

Add changelog for 2.1.6

---

pubspec.yaml

* [Fix load state errors](https://github.com/Workiva/r_tree/pull/71)
* [Add changelog for 2.1.6](https://github.com/Workiva/r_tree/pull/72)
* [Deprecate symbols not intended to be public for upcoming 3.0 release](https://github.com/Workiva/r_tree/pull/73)
Requested by: @travissanderson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/2.1.5...Workiva:release_r_tree_2.1.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/2.1.5...2.1.6
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6122762573840384/logs/)
This pull request can be recreated by clicking …

RM-222909 Release r_tree 2.1.6

---

pubspec.yaml

* [FEDX-819 Finish Github Actions transition](https://github.com/Workiva/r_tree/pull/77)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/r_tree/pull/78)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/r_tree/pull/79)
Requested by: @robbecker-wf
@Workiva/release-management-p
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/r_tree/compare/3.0.0...Workiva:release_r_tree_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/r_tree/compare/3.0.0...3.0.1
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/6122762573840384/logs/)
This pull request can be recreated by clicking …

RM-225390 Release r_tree 3.0.1
